### ISSUE TITLE
Exclude hidden tabs from count

### ISSUE THREAD

**Issue by nkakouros** [lllusion3418/webext_tab_number#3]
I am using the [Simple Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups) addon, which hides tabs to support tab groups. It would be very helpful to have the tab count be per group, i.e. show only the visible counts each time.

**Comment by lllusion3418** [comment]
So I coded something together (36986c2d40d212a963520c5762679f3bf8c0eaf8) but I'm wondering whether I should just drop support for Firefox 61 and below (#2) because it's getting way too complex at this point.

Originally I kept support for the (lack of) features because
1. I'm using nightly and they haven't even landed in stable yet, especially not in ESR
2. it would make it easier to port to other browsers

but it doesn't seem remotely worth it even though some people are _still_ using Firefox versions in the 50s for some reason (according to Firefox telemetry which _Mozilla_ collects and provides addon authors access to).

**Comment by nkakouros** [comment]
If you ask me, I would just mention the latest stable version compatible with version =< 61 as such in the README/addon description and then drop support for old versions. I guess addons.mozilla.org simply keeps you at the old version of an addon if newer versions of the addon are not compatible with your version of firefox. If so, that would simplify everything.

**Comment by nkakouros** [comment]
BTW, I tested the `hidden_tabs` branch and seems to work great! One thing only, I didn't find an option in the settings to disable this behavior, perhaps some people would like to turn this off (not me).

**Comment by lllusion3418** [comment]
Yeah, maybe I'll add some options if I do #2 (which I'm getting up to date atm), but otherwise definitely not.

I'm not sure how to do this, though:
* one option would be to add an general "exclude hidden tabs" option
* another option that would go better with the ability to display multiple lines would be to add another "scope" (global with hidden tabs) and maybe even allow the user to choose various combinations (e.g. current window excluding hidden tabs + global count including hidden tabs)

the latter would obviously be more complicated but it would fit in better with the rest.

Considering that the multiple rows thing doesn't work all that well in general (the text is tiny!) I'll probably do the first one.

**Comment by lllusion3418** [comment]
So I made a pre-release [here](https://github.com/lllusion3418/webext_tab_number/releases/tag/v0.12-alpha2) but since it's getting late today and since I won't have much time next week in case I missed something, I'll wait before making a proper release.

Feel free to help testing it (I'm not even using any tab hiding addons and only tested it on nightly, though not even all settings).

I thought, I'd name the option "_include_ hidden tabs" and make it the default since you usually wouldn't expect that behavior at all, I'd think.

Here's the somewhat simpler new commit - with settings: 0f975460a3f5da00c133900762a03eb4e21ac944

**Comment by nkakouros** [comment]
I installed it and it works fine so far.

Edit 27 Jun 2021: Still working without any issue.

**Comment by lllusion3418** [comment]
Finally made a release (not extensively tested - that's why I put it off for so long)

Thanks for the feedback, though.
